const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Tilemap,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Background: 0},
	{TiledBackground: 0},
	{Life: 0},
	{Mirrored: 0},
	{IsDead: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Tween: 0},
	{Wolf: 0},
	{Keyboard: 0},
	{Coin: 0},
	{Pin: 0},
	{ScoreText: 0},
	{Audio: 0},
	{Tilemap: 0},
	{Chicken: 0},
	{Eyeball: 0},
	{State: 0},
	{Skeleton: 0},
	{Heart: 0},
	{Heart2: 0},
	{Heart3: 0},
	{Bullet: 0},
	{Fireball: 0},
	{PopText: 0},
	{TitleText: 0},
	{PressText: 0},
	{Flag: 0},
	{Confeti: 0},
	{exteriorparallaxBG: 0},
	{FinalScoreText: 0},
	{FinaMssg: 0},
	{GameOverText: 0},
	{Score: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Wolf: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Coin: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Chicken: class extends self.ISpriteInstance {},
	Eyeball: class extends self.ISpriteInstance {},
	Skeleton: class extends self.ISpriteInstance {},
	Heart: class extends self.ISpriteInstance {},
	Heart2: class extends self.ISpriteInstance {},
	Heart3: class extends self.ISpriteInstance {},
	Fireball: class extends self.ISpriteInstance {},
	PopText: class extends self.ITextInstance {},
	TitleText: class extends self.ITextInstance {},
	PressText: class extends self.ITextInstance {},
	Flag: class extends self.ISpriteInstance {},
	Confeti: class extends self.ISpriteInstance {},
	exteriorparallaxBG: class extends self.ISpriteInstance {},
	FinalScoreText: class extends self.ITextInstance {},
	FinaMssg: class extends self.ITextInstance {},
	GameOverText: class extends self.ITextInstance {}
}